# Generated by Django 3.2.5 on 2021-07-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id_company',
            new_name='company',
        ),
    ]
