# Generated by Django 3.2.5 on 2021-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('status_transactio', models.CharField(max_length=50)),
                ('status_aprproved', models.BooleanField()),
            ],
        ),
    ]
