# Generated by Django 3.2.5 on 2021-07-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='status_aprproved',
            new_name='status_approved',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='status_transactio',
            new_name='status_transaction',
        ),
    ]
